/**
 * Dev/TherifyAdminAPI
 * A dev instance of the TherifyAdminAPI
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("matchesCompanyIdGet", () => {
    const companyId: number = 56
    return expect(instance.matchesCompanyIdGet(companyId, {})).resolves.toBe(null)
  })
})

